### ISSUE TITLE
debugger 1.6.8 not playing ball with ruby 2.2.1

### ISSUE THREAD

**Issue by iambmelt** [jasonjoh/o365-tutorial#2]
``` bash
Installing debugger 1.6.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    /Users/brianmel/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150824-8966-18m4kv9.rb extconf.rb
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
    --with-opt-dir
    --without-opt-dir
    --with-opt-include
    --without-opt-include=${opt-dir}/include
    --with-opt-lib
    --without-opt-lib=${opt-dir}/lib
    --with-make-prog
    --without-make-prog
    --srcdir=.
    --curdir
    --ruby=/Users/brianmel/.rvm/rubies/ruby-2.2.1/bin/$(RUBY_BASE_NAME)
/Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `initialize': No such file or directory @ rb_sysopen - ./221/ruby_debug.h (Errno::ENOENT)
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `open'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1391:in `copy_file'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:485:in `copy_file'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:402:in `block in cp'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1570:in `block in fu_each_src_dest'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1584:in `fu_each_src_dest0'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:1568:in `fu_each_src_dest'
    from /Users/brianmel/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/fileutils.rb:401:in `cp'
    from extconf.rb:83:in `block in <main>'
    from extconf.rb:82:in `each'
    from extconf.rb:82:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/brianmel/.rvm/gems/ruby-2.2.1/gems/debugger-1.6.8 for inspection.
Results logged to /Users/brianmel/.rvm/gems/ruby-2.2.1/extensions/x86_64-darwin-14/2.2.0-static/debugger-1.6.8/gem_make.out
An error occurred while installing debugger (1.6.8), and Bundler cannot continue.
Make sure that `gem install debugger -v '1.6.8'` succeeds before bundling.
```

**Comment by jasonjoh** [comment]
Thanks for the report! The sample actually doesn't even use the debugger gem, it's just added by default when generating the app with `rails new o365-tutorial`. Does it still put debugger in the gemfile if you create a new app with Ruby 2.2.1 installed?

**Comment by iambmelt** [comment]
@jasonjoh it doesn't - here's the template Gemfile produced by `rails new x`

``` ruby
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.3'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end
```

**Comment by jasonjoh** [comment]
Ok. Well changing this to `byebug` breaks the app for Ruby 1.9.3, which is the version I used to create the app originally. I don't use it either way, so it's not a huge deal, we just want the app to build! I'm going to leave this as `debugger` in the repository and instead update the README to clarify that v1.9.3 was used to create this, and if you are using >= v2, you need to change it to `byebug` if you download or fork the repository. Sound fair?

**Comment by jasonjoh** [comment]
Actually, maybe even better:

```
# Check version. byebug works with version 2.*, but not with 1.*
# debugger works with 1.*, but not with 2.*
if RUBY_VERSION.start_with?('2')
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
else
  # Call 'debugger' anywhere in the code to stop execution and get a debugger console
  gem 'debugger'
end
```

**Comment by iambmelt** [comment]
@jasonjoh Thanks for taking a look! :+1:
